name: "githubaction02-test"
on: 
  push: 
    branches: 
      - 'main'
      - 'features/**'

jobs: 
  fst_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build
